version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: chat_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  chat_backend:
    build: .
    container_name: chat_backend
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

volumes:
  mongo_data:
